/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RecordId = IDL.Nat;
export const Statut = IDL.Text;
export const Timestamp = IDL.Int;
export const DemandeBase = IDL.Record({
  'id' : RecordId,
  'nom' : IDL.Text,
  'statut' : Statut,
  'date' : Timestamp,
  'email' : IDL.Text,
  'departement' : IDL.Text,
  'message' : IDL.Text,
  'telephone' : IDL.Text,
});
export const DemandeInput = IDL.Record({
  'nom' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'telephone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContacts' : IDL.Func([], [IDL.Vec(DemandeBase)], ['query']),
  'getDemandesImmobilier' : IDL.Func([], [IDL.Vec(DemandeBase)], ['query']),
  'getDemandesNettoiement' : IDL.Func([], [IDL.Vec(DemandeBase)], ['query']),
  'getDemandesVoyages' : IDL.Func([], [IDL.Vec(DemandeBase)], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitContact' : IDL.Func([DemandeInput], [RecordId], []),
  'submitImmobilier' : IDL.Func([DemandeInput], [RecordId], []),
  'submitNettoiement' : IDL.Func([DemandeInput], [RecordId], []),
  'submitVoyage' : IDL.Func([DemandeInput], [RecordId], []),
  'updateStatut' : IDL.Func([IDL.Text, RecordId, Statut], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RecordId = IDL.Nat;
  const Statut = IDL.Text;
  const Timestamp = IDL.Int;
  const DemandeBase = IDL.Record({
    'id' : RecordId,
    'nom' : IDL.Text,
    'statut' : Statut,
    'date' : Timestamp,
    'email' : IDL.Text,
    'departement' : IDL.Text,
    'message' : IDL.Text,
    'telephone' : IDL.Text,
  });
  const DemandeInput = IDL.Record({
    'nom' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'telephone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContacts' : IDL.Func([], [IDL.Vec(DemandeBase)], ['query']),
    'getDemandesImmobilier' : IDL.Func([], [IDL.Vec(DemandeBase)], ['query']),
    'getDemandesNettoiement' : IDL.Func([], [IDL.Vec(DemandeBase)], ['query']),
    'getDemandesVoyages' : IDL.Func([], [IDL.Vec(DemandeBase)], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitContact' : IDL.Func([DemandeInput], [RecordId], []),
    'submitImmobilier' : IDL.Func([DemandeInput], [RecordId], []),
    'submitNettoiement' : IDL.Func([DemandeInput], [RecordId], []),
    'submitVoyage' : IDL.Func([DemandeInput], [RecordId], []),
    'updateStatut' : IDL.Func([IDL.Text, RecordId, Statut], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };