/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DemandeBase {
  'id' : RecordId,
  'nom' : string,
  'statut' : Statut,
  'date' : Timestamp,
  'email' : string,
  'departement' : string,
  'message' : string,
  'telephone' : string,
}
export interface DemandeInput {
  'nom' : string,
  'email' : string,
  'message' : string,
  'telephone' : string,
}
export type RecordId = bigint;
export type Statut = string;
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContacts' : ActorMethod<[], Array<DemandeBase>>,
  'getDemandesImmobilier' : ActorMethod<[], Array<DemandeBase>>,
  'getDemandesNettoiement' : ActorMethod<[], Array<DemandeBase>>,
  'getDemandesVoyages' : ActorMethod<[], Array<DemandeBase>>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitContact' : ActorMethod<[DemandeInput], RecordId>,
  'submitImmobilier' : ActorMethod<[DemandeInput], RecordId>,
  'submitNettoiement' : ActorMethod<[DemandeInput], RecordId>,
  'submitVoyage' : ActorMethod<[DemandeInput], RecordId>,
  'updateStatut' : ActorMethod<[string, RecordId, Statut], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];